services:
  - type: web
    name: url-shortener-auto
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 4 --threads 4 --timeout 120
